# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0002_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventary.Estado'),
            preserve_default=False,
        ),
    ]
