# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0003_computer_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='equipo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='modelo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
