# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0004_auto_20170831_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='nom_usuario',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='sis_operativo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
