# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0005_auto_20170831_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='modelo',
        ),
    ]
